%% Start sine stim script

% deliver 5 sine wave stimulus amplitudes using protocols as I will for the experiment {0.5, 1, 2, 4}.  Establishing only these amps and freqs as possibilities for now

displacements = 0.05*sqrt(2).^(0:6);
freqs = 25 * sqrt(2) .^ (0:10);
displacementOffset =1;
% displacement = 1;
% freqs = 25 * 2 .^ (2:5);
%displacement = 3;
%freqs = 200;

A = Acquisition; 
A.setProtocol('PiezoSine','modusOperandi','Cal');
A.protocol.setParams('ramptime',.04,...
    'stimDurInSec',1,...
    'preDurInSec',1,...
    'postDurInSec',1,...
    'displacements',1,...
    'freqs',1,...
    'displacement',3,...
    'freq',1,...
    'displacementOffset',5)
